# Generated by Django 5.0.2 on 2025-08-28 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, verbose_name='OTP Code')),
                ('purpose', models.PositiveSmallIntegerField(choices=[(1, 'Password Reset'), (2, 'Register'), (3, 'Login'), (4, 'Two-Factor Authentication'), (5, 'Email Verification'), (6, 'Phone Number Change')], max_length=30, verbose_name='OTP Purpose')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('is_used', models.BooleanField(default=False, verbose_name='Is Used')),
                ('expires_at', models.DateTimeField(verbose_name='Expires At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otps', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
