# Generated by Django 5.0.2 on 2025-08-28 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='user',
        ),
        migrations.AddField(
            model_name='otp',
            name='phone_number',
            field=models.CharField(default=12, max_length=15, verbose_name='Phone Number'),
            preserve_default=False,
        ),
    ]
