# Generated by Django 5.0.2 on 2025-08-30 22:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('member', 'Member'), ('admin', 'Admin'), ('owner', 'Owner'), ('moderator', 'Moderator')], max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('muted_until', models.DateTimeField(blank=True, null=True)),
                ('permissions', models.JSONField(blank=True, null=True)),
                ('is_banned', models.BooleanField(default=False)),
                ('last_read_message_id', models.UUIDField(blank=True, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='conversations.conversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['conversation', 'user'], name='conversatio_convers_ee3798_idx')],
                'unique_together': {('conversation', 'user')},
            },
        ),
    ]
