# Generated by Django 5.0.2 on 2025-09-16 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0002_message_conversationmember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationmember',
            name='permissions',
            field=models.JSONField(blank=True, default={'can_delete': False, 'can_invite': False, 'can_send': True}, null=True),
        ),
    ]
