# Generated by Django 5.0.2 on 2025-09-17 16:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0003_alter_conversationmember_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversationmember',
            name='last_read_message_id',
        ),
        migrations.AddField(
            model_name='message',
            name='seen_by',
            field=models.ManyToManyField(related_name='seen_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
