# Generated by Django 5.0.2 on 2025-09-06 20:27

import conversations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0005_alter_message_receiver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=conversations.models.message_attachment_path),
        ),
    ]
